name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Go v${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
        - "1.16.x"
        - "1.17.x"
        - "1.18.x"
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v -o bogo ./cmd/bogo

    - name: Test
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash)
